all: parser

parser: Bag.cpp Board.cpp ConsolePrinter.cpp Dictionary.cpp Exchange.cpp Move.cpp Passmove.cpp PlaceMove.cpp Player.cpp main.cpp
    g++ -g -Wall -std=c++11 Bag.cpp Board.cpp ConsolePrinter.cpp Dictionary.cpp Exhange.cpp Move.cpp PassMove.cpp PlaceMove.cpp Player.cpp main.cpp -o scrabble